//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LampShop.LampService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LampService", ConfigurationName="LampService.ILamp")]
    public interface ILamp {
        
        [System.ServiceModel.OperationContractAttribute(Action="LampService/ILamp/GetAll", ReplyAction="LampService/ILamp/GetAllResponse")]
        RepositoryInterface.Models.Lamp[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="LampService/ILamp/GetAll", ReplyAction="LampService/ILamp/GetAllResponse")]
        System.Threading.Tasks.Task<RepositoryInterface.Models.Lamp[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILampChannel : LampShop.LampService.ILamp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LampClient : System.ServiceModel.ClientBase<LampShop.LampService.ILamp>, LampShop.LampService.ILamp {
        
        public LampClient() {
        }
        
        public LampClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LampClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LampClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LampClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RepositoryInterface.Models.Lamp[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<RepositoryInterface.Models.Lamp[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
