//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LampShop.LightBulpService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LightBulpService.ILightBulbService")]
    public interface ILightBulbService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILightBulbService/GetLightBulb", ReplyAction="http://tempuri.org/ILightBulbService/GetLightBulbResponse")]
        string GetLightBulb(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILightBulbService/GetLightBulb", ReplyAction="http://tempuri.org/ILightBulbService/GetLightBulbResponse")]
        System.Threading.Tasks.Task<string> GetLightBulbAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILightBulbServiceChannel : LampShop.LightBulpService.ILightBulbService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LightBulbServiceClient : System.ServiceModel.ClientBase<LampShop.LightBulpService.ILightBulbService>, LampShop.LightBulpService.ILightBulbService {
        
        public LightBulbServiceClient() {
        }
        
        public LightBulbServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LightBulbServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LightBulbServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LightBulbServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLightBulb(int value) {
            return base.Channel.GetLightBulb(value);
        }
        
        public System.Threading.Tasks.Task<string> GetLightBulbAsync(int value) {
            return base.Channel.GetLightBulbAsync(value);
        }
    }
}
